import {
  EMPLOYMENT_STATUSES,
  GENDER_OPTIONS,
  STRESS_EVENTS,
  TREATMENT_OBJECTIVES,
  THERAPIST_GENDER_PREFS,
  SESSION_FORMAT_PREFS,
  THERAPY_APPROACH_PREFS,
  WEEKDAYS,
  TIME_WINDOWS,
  WHO_IDEAS,
  WHO_OPTIONS,
  CHEAT_OPTIONS,
  CONSENT_ITEMS,
  COUNSELLING_OUTCOMES,
  SENSITIVE_PRIVACY_MESSAGE,
} from './coupleTherapyConfig';

export const COUPLE_INTAKE_SECTIONS = [
  {
    id: 'personal',
    title: 'Personal information',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      { name: 'fullName', type: 'text', label: 'Full name', required: true },
      { name: 'dateOfBirth', type: 'birthdate', label: 'Date of birth', required: true },
      { name: 'age', type: 'text', label: 'Age', readOnly: true },
      { name: 'gender', type: 'chips', label: 'Gender identity', options: GENDER_OPTIONS, required: true },
      { name: 'ethnicity', type: 'text', label: 'Ethnicity (optional)' },
      { name: 'religion', type: 'text', label: 'Religion (optional)' },
      { name: 'address', type: 'text', label: 'Home address', required: true },
      { name: 'phoneCell', type: 'phone', label: 'Cell phone', required: true },
      { name: 'phoneHome', type: 'phone', label: 'Home phone (optional)' },
      { name: 'phoneWork', type: 'phone', label: 'Work phone (optional)' },
      { name: 'email', type: 'email', label: 'Email', required: true },
      { name: 'emergencyContactName', type: 'text', label: 'Emergency contact name', required: true },
      { name: 'emergencyContactPhone', type: 'phone', label: 'Emergency contact phone', required: true },
    ],
  },
  {
    id: 'employment',
    title: 'Employment & life situation',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      { name: 'employmentStatus', type: 'chips', label: 'Employment status', options: EMPLOYMENT_STATUSES, required: true },
      { name: 'employerName', type: 'text', label: 'Employer or institution name' },
      { name: 'position', type: 'text', label: 'Position or role' },
      { name: 'notWorkingReason', type: 'text', label: 'If not working — reason' },
      { name: 'livesWith', type: 'text', label: 'Who do you currently live with?', required: true },
      { name: 'childrenCount', type: 'number', label: 'Number of children', required: true },
      { name: 'childrenAges', type: 'text', label: "Children's ages", placeholder: 'e.g. 5, 12' },
    ],
  },
  {
    id: 'psychiatric',
    title: 'Psychiatric & medical history',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      { name: 'mentalHealthConditions', type: 'textarea', label: 'Diagnosed mental health conditions (list)' },
      { name: 'physicalConditions', type: 'textarea', label: 'Diagnosed physical or medical conditions (list)' },
      { name: 'currentMedications', type: 'textarea', label: 'Current medications and what each is taken for' },
      { name: 'familyDoctorName', type: 'text', label: 'Family doctor name' },
      { name: 'familyDoctorPhone', type: 'phone', label: 'Family doctor phone' },
      { name: 'familyDoctorLastVisit', type: 'date', label: 'Date of last check-up' },
      { name: 'psychiatristName', type: 'text', label: 'Psychiatrist name (if applicable)' },
      { name: 'psychiatristPhone', type: 'phone', label: 'Psychiatrist phone' },
      { name: 'psychiatristLastVisit', type: 'date', label: 'Date of last psychiatrist visit' },
    ],
  },
  {
    id: 'treatment',
    title: 'Mental health treatment history',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      {
        name: 'hospitalizedPsych',
        type: 'yesno_text',
        label: 'Ever hospitalized for psychological or psychiatric reasons?',
        textKey: 'hospitalizedPsychDetails',
        textPlaceholder: 'When, where, why',
      },
      {
        name: 'previousCoupleCounselling',
        type: 'yesno_text',
        label: 'Previous couple counselling?',
        textKey: 'previousCoupleWhenWhere',
        textPlaceholder: 'When, where, with whom, how long',
      },
      {
        name: 'previousCoupleOutcome',
        type: 'chips',
        label: 'If yes — outcome',
        options: COUNSELLING_OUTCOMES,
      },
      {
        name: 'previousIndividualTherapy',
        type: 'yesno_text',
        label: 'Previous individual therapy?',
        textKey: 'previousIndividualSummary',
        textPlaceholder: 'Brief summary of issues addressed',
      },
    ],
  },
  {
    id: 'habits',
    title: 'Current habits',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      { name: 'smoking', type: 'textarea', label: 'Smoking (describe)' },
      { name: 'alcoholUse', type: 'textarea', label: 'Alcohol use (describe)' },
      { name: 'drugUse', type: 'textarea', label: 'Drug use (describe)' },
      { name: 'gambling', type: 'textarea', label: 'Gambling (describe)' },
      { name: 'caffeine', type: 'textarea', label: 'Caffeine intake (describe)' },
      { name: 'exercise', type: 'textarea', label: 'Exercise routine (describe)' },
      { name: 'sleepPatterns', type: 'textarea', label: 'Sleep patterns (describe)' },
      { name: 'eatingHabits', type: 'textarea', label: 'Eating habits (describe)' },
      { name: 'hobbiesRelaxation', type: 'textarea', label: 'Hobbies and relaxation (describe)' },
    ],
  },
  {
    id: 'stress',
    title: 'Stressful life events',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: STRESS_EVENTS.map((e) => ({
      name: `stress_${e.key}`,
      type: 'yesno_text',
      label: e.label,
      textKey: `stress_${e.key}_details`,
    })),
  },
  {
    id: 'relationship',
    title: 'About your relationship',
    subtitle: 'Your private perspective — your partner answers separately',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      { name: 'relationshipDuration', type: 'text', label: 'How long have you been together?', required: true },
      {
        name: 'relationshipStatusDetail',
        type: 'text',
        label: 'Current status (married, cohabiting, dating, separated, engaged)',
        required: true,
      },
      { name: 'childrenTogether', type: 'yesno_text', label: 'Do you have children together?', textKey: 'childrenTogetherDetails', textPlaceholder: 'How many and ages' },
      { name: 'relationshipSatisfaction', type: 'scale', label: 'Relationship satisfaction (1–10)', min: 1, max: 10, required: true },
      { name: 'counsellingExpectations', type: 'textarea', label: 'Personal expectations from counselling', required: true },
      { name: 'treatmentObjectives', type: 'multiselect', label: 'Treatment objectives', options: TREATMENT_OBJECTIVES, required: true },
      { name: 'treatmentObjectivesOther', type: 'text', label: 'Other objectives (if selected)' },
      { name: 'alreadyTried', type: 'textarea', label: 'What have you already tried to address these issues?' },
      { name: 'whoseIdea', type: 'chips', label: 'Whose idea was it to come to therapy?', options: WHO_IDEAS, required: true },
      { name: 'promptingEvent', type: 'textarea', label: 'Was there a specific event that triggered seeking help now?' },
      { name: 'coupleStrengths', type: 'textarea', label: 'Biggest strengths of your relationship', required: true },
      { name: 'personalImprovement1', type: 'text', label: 'One thing you could do to improve the relationship', required: true },
      { name: 'personalImprovement2', type: 'text', label: 'Second thing you could do', required: true },
      { name: 'personalImprovement3', type: 'text', label: 'Third thing you could do', required: true },
    ],
  },
  {
    id: 'sensitive',
    title: 'Confidential screening',
    subtitle: SENSITIVE_PRIVACY_MESSAGE,
    policySlug: 'couple-therapy-sensitive-screening',
    roles: ['partnerA', 'partnerB'],
    storage: 'sensitive',
    therapistOnly: true,
    fields: [
      {
        name: 'intoxicationUse',
        type: 'yesno_text',
        label: 'Does either you or your partner drink alcohol or use drugs to intoxication?',
        textKey: 'intoxicationDetails',
      },
      {
        name: 'physicalHarm',
        type: 'yesno_text',
        label: 'Has either partner physically restrained, pushed, slapped, grabbed, or harmed the other?',
        textKey: 'physicalHarmDetails',
      },
      {
        name: 'threatenedSeparation',
        type: 'yesno_text',
        label: 'Has either partner threatened to separate or divorce?',
        textKey: 'threatenedSeparationWho',
      },
      {
        name: 'consultedLawyer',
        type: 'yesno_text',
        label: 'Has either partner consulted a lawyer about separation or divorce?',
        textKey: 'consultedLawyerWho',
      },
      { name: 'infidelity', type: 'chips', label: 'Emotional or physical cheating?', options: CHEAT_OPTIONS, required: true },
      { name: 'infidelityWho', type: 'chips', label: 'If applicable — who?', options: WHO_OPTIONS },
      {
        name: 'partnerWithdrawn',
        type: 'yesno_text',
        label: 'Do you feel either partner has emotionally withdrawn?',
        textKey: 'partnerWithdrawnWho',
      },
      { name: 'sexualSatisfaction', type: 'scale', label: 'Sexual satisfaction (1–10)', min: 1, max: 10, required: true },
      { name: 'sexualSatisfactionComment', type: 'textarea', label: 'Optional comment on sexual satisfaction' },
      { name: 'therapistPrivateNotes', type: 'textarea', label: 'Anything else your therapist should know privately?' },
    ],
  },
  {
    id: 'preferences',
    title: 'Therapist preferences & scheduling',
    roles: ['partnerA', 'partnerB'],
    storage: 'private',
    fields: [
      { name: 'therapistGenderPref', type: 'chips', label: 'Preferred therapist gender', options: THERAPIST_GENDER_PREFS, required: true },
      { name: 'sessionFormatPref', type: 'chips', label: 'Session format', options: SESSION_FORMAT_PREFS, required: true },
      { name: 'therapyApproachPref', type: 'chips', label: 'Therapy approach', options: THERAPY_APPROACH_PREFS, required: true },
      { name: 'therapyApproachOther', type: 'text', label: 'Other approach (if selected)' },
      { name: 'therapistRequirements', type: 'textarea', label: 'Specific requirements (language, culture, religion, etc.)' },
      { name: 'availabilityDays', type: 'multiselect', label: 'Available days', options: WEEKDAYS, required: true },
      { name: 'availabilityWindows', type: 'multiselect', label: 'Preferred time windows', options: TIME_WINDOWS, required: true },
      { name: 'availabilityNotes', type: 'textarea', label: 'Additional scheduling notes (optional)' },
    ],
  },
  {
    id: 'consent',
    title: 'Consent & agreements',
    roles: ['partnerA', 'partnerB'],
    storage: 'consent',
    fields: CONSENT_ITEMS.map((c) => ({
      name: c.key,
      type: 'consent_check',
      label: c.title,
      description: c.description,
      policySlug: c.policySlug,
      required: true,
    })).concat([
      { name: 'signature', type: 'signature', label: 'Electronic signature (full legal name)', required: true },
    ]),
  },
];

export function sectionsForPartner(partnerRole) {
  const key = partnerRole === 'partnerB' ? 'partnerB' : 'partnerA';
  return COUPLE_INTAKE_SECTIONS.filter((s) => s.roles.includes(key));
}
